//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interview_crud.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblemployee
    {
        [Required]
        public int emp_id { get; set; }
        [Required]
        [Display(Name =" employee name")]
        [StringLength(10,MinimumLength =5,ErrorMessage ="length between 5 to 10 character")]
        
        public string emp_name { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        public string emp_address { get; set; }
        [Required]
        [StringLength(10,ErrorMessage ="enter valid mobile number")]
        
        public string emp_mob { get; set; }
        [Required]
        public Nullable<System.DateTime> emp_dob { get; set; }
        [Required]
        public string emp_hob { get; set; }
        [Required]
        public string emp_gender { get; set; }
        [Required]
        public string emp_profile { get; set; }
        [Required]
        public string emp_status { get; set; }
        [Required]
        public Nullable<int> country_id { get; set; }
        [Required]
        public Nullable<int> state_id { get; set; }
        [Required]
        public Nullable<int> city_id { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
